spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   #开发环境
  application:
    name: springcloud-config-cstn-dev
---
spring:
  profiles: test  #测试环境
  application:
    name: springcloud-config-cstn-test

#UTF-8保存
